### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by supermaverickws** [zgatrying/react-native-ezvizview#2]
![image](https://user-images.githubusercontent.com/61172354/122664373-956a2c00-d1d3-11eb-8330-a1552cc92a23.png)

**Comment by supermaverickws** [comment]
库不支持模拟器，跑模拟器会报错。跑真机正常。

**Comment by guotianwu** [comment]
react-native 版本0.64能集成起来用吗？

**Comment by zgatrying** [comment]
> react-native 版本0.64能集成起来用吗？

能，示例项目用的react-native 0.63版，版本跨度不大的。倒是0.60以前的版本没有试过。

**Comment by zgatrying** [comment]
> 库不支持模拟器，跑模拟器会报错。跑真机正常。

我记得萤石官方文档里有提到sdk不支持模拟器环境运行的。

**Comment by supermaverickws** [comment]
eact-native 0.64.2 能用。没 x86 很不友好。公司的wifi 有问题。我联真机调试困难。

**Comment by guotianwu** [comment]
@zgatrying @supermaverickws 
![image](https://user-images.githubusercontent.com/13671367/123603415-70596700-d82c-11eb-9988-75657bf0d4b2.png)
我的环境是react-native 0.64.2
 pod 1.10.1
使用ts
直接真机测试，真机的页面是直接卡住了

**Comment by zgatrying** [comment]
> @zgatrying @supermaverickws
> ![image](https://user-images.githubusercontent.com/13671367/123603415-70596700-d82c-11eb-9988-75657bf0d4b2.png)
> 我的环境是react-native 0.64.2
> pod 1.10.1
> 使用ts
> 直接真机测试，真机的页面是直接卡住了

建议根据萤石官网sdk文档ios sdk部分，检查依赖和权限是不是配置正确。
